version: "3.8"

services:
  # Backend Service
  finaware-server:
    image: wisekingdavid/finaware-server:latest
    restart: on-failure
    ports:
      - "9000:9000"
    depends_on:
      - PostgreSQL
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/finaware-db
      - SPRING_DATASOURCE_USERNAME=finaware-postgres
      - SPRING_DATASOURCE_PASSWORD=finaware-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - backend
      - frontend

  # Frontend Service
  finaware-client:
    image: wisekingdavid/finaware-client:latest
    ports:
      - "4200:80"
    restart: always
    depends_on:
      - finaware-server
    networks:
      - frontend

  # Database
  PostgreSQL:
    image: postgres
    container_name: finaware-postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=finaware-postgres
      - POSTGRES_PASSWORD=finaware-postgres
      - POSTGRES_DB=finaware-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

networks:
  backend:
  frontend:
